### ISSUE TITLE
Should we continue to use spdep?

### ISSUE THREAD

**Issue by krpaulson** [aboskovic21/STAB#6]
Should we remove use of `spdep` package? We are currently using the `poly2nb` and `nb2mat` functions. This package works fine with `sf` objects but it would be good to know if there is a preferred alternative for `sf`.

**Comment by krpaulson** [comment]
Here's an example of where we are using these functions: https://github.com/aboskovic21/STAB/blob/main/2023-554/2023-554-PrevalenceMapping-R.Rmd#L86-L87

**Comment by edzer** [comment]
`spdep` is not going to retire, afaict.

**Comment by edzer** [comment]
There is a package called `sfdep`, but I believe it's an alternative interface to `spdep` rather than an alternative for it.

**Comment by krpaulson** [comment]
Thanks for the input. I think let's keep `spdep` then at least for now.
